[package]
name = "fedimoji"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
image = "0.25.1"
serde = { version = "1.0.204" }
serde_json = "1.0.120"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
